### ISSUE TITLE
Configuration change in exesting installation is not working

### ISSUE THREAD

**Issue by valvin1** [friendica/docker#101]
I'm using version 2019.12 and I get two times issue when changing configuration using my environment variables that were not reflected. 

I think these two issues are linked. In both cases I had to modify manually local-config.php where changes were not reflected. 

My uses cases are : 

* I want to add a new admin user : here in addition i'm wondering if the parameter has the good name `admin_mail` instead of `admin_email` : [corresponding code](https://github.com/friendica/docker/blob/master/2019.12/apache/config/zz-docker.config.php#L32)
* I change the host and the password of my database : i'm wondering if in that case the issue is that these settings are only used in the installation process with autoinstall.

**Comment by focalfury** [comment]
not an expert by any means but I do believe those params are only used for auto installation.  Even if you didn't provide them you could go set up the database manually and friendica settings in the config files to get it working.

**Comment by valvin1** [comment]
You are right but I'm not sure it is what we can except in a docker installation.
Modifying local files is working but it is not usual to do so in a container setup with env variables.

**Comment by nupplaphil** [comment]
> My uses cases are :
> 
>     * I want to add a new admin user : here in addition i'm wondering if the parameter has the good name `admin_mail` instead of `admin_email` : [corresponding code](https://github.com/friendica/docker/blob/master/2019.12/apache/config/zz-docker.config.php#L32)

This is indeed a bug .. it should be the same config name like the db-entry

> 
>     * I change the host and the password of my database : i'm wondering if in that case the issue is that these settings are only used in the installation process with autoinstall.

You and @focalfury are right. The current problem is that we persist the dbhost/user/name into the `config/local.config.php`, which makes it impossible to change it through the parameter again.

A fix would be to avoid saving any entry into the `local.config.php` file and instead load it through the environment variables.

This seems possible, I'll give it a try

**Comment by nupplaphil** [comment]
Fixed per https://github.com/friendica/friendica/pull/9422
