### ISSUE TITLE
"Can't connect to site" when I try to login after installation using this image

### ISSUE THREAD

**Issue by stodge** [friendica/docker#114]
I can install Friendica and I can then create my account using this image. But when I try to login I get a blank page and an error "Can't connect to site". The site is configured for `localhost` as I'm just running it on my laptop without a domain name. Is this supported?

**Comment by nupplaphil** [comment]
A couple of questions:

- What's the URL in your address bar after loading the page? "http://localhost" or "http://127.0.0.1"  oder "http://friendica.local" or something similar?
- Did you create your account per "Create Account" function of the page or per CLI or similar?
- How did you configure it?
- what do you mean "without domain name"?

If you want to test it locally, I'd prefer another setup:
- Domain: `friendica.local`
- Add Host-entry (Windows: `%windir%\system32\drivers\etc\hosts`, linux: `/etc/hosts`) and route `friendica.local` to `127.0.0.1`

So you can use `http://friendica.local` as an URL and use it locally.

Btw. that's how a dev-setup is used, so it should work ;-)

**Comment by nupplaphil** [comment]
Closed

@stodge  feel free to reopen it in case you need support
