### ISSUE TITLE
Maintenance seemingly stuck on "updating item table"

### ISSUE THREAD

**Issue by noplanman** [friendica/docker#136]
### Expected behavior
Main page should be loading.

### Actual behavior
All pages redirect to `/maintenance`.

### Steps to reproduce the problem
I'm using docker. After updating from 2020.07-1 to 2020.09 everything seemed fine.
So i patched all files for 2020.09-1 (directly inside the container) and restarted the container.
Unfortunately the container couldn't start up again because of [this version check](https://github.com/friendica/docker/blob/ca5b039dd116f4654813baab556e75ae3f7adca8/docker-entrypoint.sh#L55).
So i deleted and rebuilt the container and did the patch manually again afterwards.
And now my instance is stuck in this maintenance. 
It doesn't seem to be doing anything, as CPU usage is very low and i don't see any changes in the DB.

Is there any manual command i can run to unlock this?

### Friendica version you encountered the problem
Around 2020.09 and 2020.09-1

### Friendica source (git, zip)
Official docker container.

### PHP version
7.3

### SQL version
MariaDB 10.4

**Comment by nupplaphil** [comment]
The `VERSION` at `/var/www/html` is now one version ahead to the original sources at `/usr/src/` and therefore the container stops for safety reason, because per default, the container copies the whole `/usr/src` over the `/var/www/html` directory, which would lead to old db and files.

You've to wait until https://github.com/docker-library/official-images/pull/8777 is merged. There are maybe other steps, but they could possible lead to other errors, so I think you've to wait at least 2-3 hours until pulling the new sources - sry

**Comment by noplanman** [comment]
@nupplaphil Thanks for your reply.
I totally understand the VERSION thing, which makes sense 👌 

The problem is that my code is basically on version 2020.09-1 but it seems to be stuck in the maintenance mode, and i have no idea what (if anything) is happening in the background.
So in that sense, I'm don't know how the new docker image should fix this, as it seems like some data block somewhere in the DB.

Is there some lock flag or something that defines when it's in maintenance mode?
Also, can a maintenance run be triggered manually? (apart from `bin/console dbstructure update`)

(The reason why I posted this issue in the core repo, was because I don't think it's docker related.)

**Comment by noplanman** [comment]
Ok, well I just found the maintenance mode setting in the console app and disabled it with `bin/console maintenance 0` and now all is good again 🤔 

Will let the queue catch up and see if everything is flowy again...

**Comment by noplanman** [comment]
Seems all good now.

I'd initially forgotten to update the new composer dependencies (`phpseclib`), which may have caused some things breaking, but now it seems like it's running smoothly again.

So I'll close off here ✌️
