### ISSUE TITLE
Stuck with "Vendor path not found" error after following Docker instructions

### ISSUE THREAD

**Issue by Jay2645** [friendica/docker#140]
Following the instructions on the main page, I get a plain white page with simply `Vendor path not found. Please execute "bin/composer.phar --no-dev install" on the command line in the web root.`

The issue is there _is_ no `bin/composer.phar`, at least not any that I can see. This is with the default docker-compose settings for an Apache server. I don't see a `bin` folder at all in `/var/www/html`:

```
CHANGELOG    Doxyfile  README.md  Vagrantfile  autotest.sh  build.xml      composer.lock  docblox.dist.xml         index.php    update.php
CREDITS.txt  LICENSE   VERSION    addon        boot.php     composer.json  database.sql   friendica_test_data.sql  ruleset.xml
```

And of course just `/bin` (as in the root directory) doesn't have anything which looks like it might fix it, either.

Any help?

**Comment by Jay2645** [comment]
Ah, it was in `/usr/src/friendica/bin/composer.phar` -- took some digging, but I found it. Might be helpful to add to the instructions. Various other folders (like the `vendor` folder) were also missing, giving errors like `Warning: require(/var/www/html/vendor/composer/../../include/conversation.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 73`.

Creating symlinks where needed gave me some headway, but then I hit another dead end with `Fatal error: Uncaught Error: Class 'Friendica\Module\Register' not found in /usr/src/friendica/boot.php:93 Stack trace: #0 /var/www/html/vendor/composer/autoload_real.php(73): require() #1 /var/www/html/vendor/composer/autoload_real.php(63): composerRequireFriendica('5ff2d7448065214...', '/var/www/html/v...') #2 /var/www/html/vendor/autoload.php(7): ComposerAutoloaderInitFriendica::getLoader() #3 /var/www/html/index.php(28): require('/var/www/html/v...') #4 {main} thrown in /usr/src/friendica/boot.php on line 93`

Trying to get around it by simply copying the while `src/friendica` folder over to `/var/www/html` got me a little bit further, but then it gave me a 404 when trying to go to `localhost:8080/install`, at which point I gave up. :)

**Comment by nupplaphil** [comment]
@Jay2645 sorry for the late answer, I was a little bit busy :/

 I do need some more information about this issue.
- Which instruction did you follow? FPM/Apache ?
- Did you use a `docker-compose.yml` file for the setup? If so, please add it here
- If not, please describe your setup as detailed as possible

I'm using the "full" friendica archive where the complete vendor directory is included, so I'm wondering what setup lead to this issue ...

**Comment by nupplaphil** [comment]
Closing it

@Jay2645 - Please don't hesitate to reopen it in case you do want or need support :)
