### ISSUE TITLE
Installation keeps going to https://friendica/index.php

### ISSUE THREAD

**Issue by jgoerzen** [friendica/docker#141]
Hi,

I was unable to complete the web-based installation because it keeps wanting to go to https://friendica/ instead of the URL given in FRIENDICA_URL.  Giving additional environment variables let it proceed that way, though.

**Comment by kiddhustle** [comment]
@jgoerzen which additional variables did you give?

**Comment by jgoerzen** [comment]
Unfortunately I no longer have that information (and discontinued my node).  Feel free to close this if you'd like.

**Comment by MrPetovan** [comment]
Sorry about that, thank you for the follow-up.
