### ISSUE TITLE
official docker image for 2021.01

### ISSUE THREAD

**Issue by valvin1** [friendica/docker#144]
Hi,

It looks everything is ready for `2021.01` image but it is not available on [docker hub](https://hub.docker.com/_/friendica?tab=description&page=1&ordering=last_updated)

If I've well understood it requires to PR something [here](https://github.com/docker-library/official-images/pulls?q=label%3Alibrary%2Ffriendica) ?

Is there another place to get image while it is approved on docker hub? :) 

Thank you

**Comment by MrPetovan** [comment]
Unfortunately, @nupplaphil has been handling the Docker image upgrade, and I'm not sure what are the steps to upgrade it with the new stable version. I could replace all the version strings in the repo to the correct one but I don't know how to push the changes to Docker Hub.

I'll give it a shot.

**Comment by nupplaphil** [comment]
Uh.. I'll do it in the next hours and add a readme about it

**Comment by MrPetovan** [comment]
I see the folders for the new version `2021.01` and `2021.03-dev` have been created already, is it just about running `generate-stackbrew-library.sh` now?

**Comment by valvin1** [comment]
@MrPetovan I think it requires to push modification to this repo which is owned by docker : https://github.com/docker-library/official-images/pulls?q=label%3Alibrary%2Ffriendica

**Comment by nupplaphil** [comment]
@valvin1 you're right :-)

**Comment by MrPetovan** [comment]
I'm going to wait for the README then.

**Comment by nupplaphil** [comment]
@valvin1 @MrPetovan -> https://github.com/docker-library/official-images/pull/9378
