### ISSUE TITLE
automatc install trouble

### ISSUE THREAD

**Issue by ghost** [friendica/docker#146]
even with the correct environment variables set, once the setup screen for the database is reached all fields are empty instead of populated as expected.

```
      - MYSQL_USER=friendica_user
      - MYSQL_PASSWORD={{ lookup('password', './settings/passwords/friendica_db_password chars=ascii_letters') }}
      - MYSQL_DATABASE=friendica_db
      - MYSQL_HOST=friendica_db
      - REDIS_HOST=friendica_redis
      - FRIENDICA_TZ={{ common_timezone }}
      - FRIENDICA_ADMIN_MAIL={{ admin_email }}
      - FRIENDICA_URL={{ service_domain }}
      - FRIENDICA_SITENAME={{ service_domain }}
      - SMTP={{ vault.smtp.host }}
      - SMTP_PORT={{ vault.smtp.port }}
      - SMTP_DOMAIN={{ domain }}
      - SMTP_FROM={{ vault.smtp.from_email }}
      - SMTP_STARTTLS=true
      - SMTP_AUTH_USER={{ vault.smtp.user }}
      - SMTP_AUTH_PASS={{ vault.smtp.pass }}
```

**Comment by nupplaphil** [comment]
The setup screen doesn't use the environment variables. They are used for the auto installation.

Plz have a look at https://github.com/friendica/docker#automatic-installation

**Comment by nupplaphil** [comment]
The setup screen doesn't use these environment variables.

@robjloranger 
Are you sure your environment variables are right?
Based on https://github.com/friendica/docker#automatic-installation , all prerequisites for the auto-installation are fulfilled, so you shouldn't even see the setup screen. Plz add the log output after the startup so I can have a look

**Comment by nupplaphil** [comment]
closed because it seems to work now
@robjloranger feel free to reopen it if necessary
