### ISSUE TITLE
official docker image 2021.04

### ISSUE THREAD

**Issue by valvin1** [friendica/docker#152]
Same as this issue : https://github.com/friendica/docker/issues/144

I've tried to PR the update.sh but it has been done by a pipeline.

So I've tried to understand the workflow and did this PR: https://github.com/docker-library/official-images/pull/10068

Don't know if it'll be accepted as I'm not the maintainer of image.

**Comment by nupplaphil** [comment]
Hi @valvin1 

I'm sorry, but I already added the PR here (just few minutes before you :D )
https://github.com/docker-library/official-images/pull/10067

Here's the HOWTO for updating this docker image:
https://github.com/friendica/docker/blob/stable/README-MAINTENANCE.md#how-to-update-the-docker-image

**Comment by nupplaphil** [comment]
Done :)
