### ISSUE TITLE
sendmail sender "Linux user"

### ISSUE THREAD

**Issue by nupplaphil** [friendica/docker#17]
The sender of each notification/email from Friendica is currently "Linux user".

That's because the "standard name" of the www-data user is "Linux user" and there is currently no overriding "From:" mechanism when using the mail() function in Friendica.

Maybe there is a php/sendmail-setting for it.

**Comment by tobiasd** [comment]
At least for mails from the admin [you can use a setting](https://github.com/friendica/friendica/blob/develop/doc/htconfig.md#administrator-options). For non-admin mails the mail sender should use the "site name" as sender name.

**Comment by nupplaphil** [comment]
Works for me now in both of my environments ( friendica.philipp.info & opensocial.at )
