### ISSUE TITLE
Docker hub - can't pull image 2021.09

### ISSUE THREAD

**Issue by valvin1** [friendica/docker#171]
Hi,

It looks like something is broken in the new docker image version. It is mising arch on 2021.09* tags so when I try to pull it I get:

```
Trying to pull docker.io/library/friendica:2021.09...
Error: choosing an image from manifest list docker://friendica:2021.09: no image found in manifest list for architecture amd64, variant "", OS linux
```

Effectively on docker hub I don't see architecture associated to tags contrary to other tags:

![image](https://user-images.githubusercontent.com/1267915/135719003-f002c6b5-e199-4a64-ba59-9b58699efaac.png)

**Comment by nupplaphil** [comment]
Yes, I already added a fix at official-images https://github.com/docker-library/official-images/pull/11008 .. I added the wrong sha256 sum for the images :X

**Comment by nupplaphil** [comment]
Now it worked :)

**Comment by elrido** [comment]
Thank you for your efforts. Currently the [amd64 image for 2021.09-fpm-alpine](https://hub.docker.com/_/friendica?tab=tags&page=1&ordering=last_updated&name=2021.09-fpm-alpine) is still missing, but the arm ones (v6, v7 and arm64/v8) got published. Were there any issues building the amd64 one?

**Comment by elrido** [comment]
I attempted to use the stable-fpm-alpine image which has gotten an amd64 image published around the same time. It seems to still contain 2021.07 in it's /usr/src/friendica.

The ppc64 image has now appeared under the 2021.09-fpm-alpine tag, so maybe I just have to be a bit more patient. :-)

**Comment by MrPetovan** [comment]
There was no 2021.07 release, are you sure it's the right one?

**Comment by elrido** [comment]
https://github.com/friendica/friendica/releases/tag/2021.07 ?

Edit: Oh, and I see that now theres an amd64 image for [2021.09](https://hub.docker.com/_/friendica?tab=tags&page=1&ordering=last_updated&name=2021.09-fpm-alpine). I was impatient - let me try that upgrade again.

**Comment by MrPetovan** [comment]
Ah, sorry, I forgot about it, usually there are 3 months between releases and the last one was `2021.09`, hence my confusion.
