### ISSUE TITLE
Upload and Memory limits

### ISSUE THREAD

**Issue by ne20002** [friendica/docker#176]
Can we have an easy was to support setting PHP values?
Example: Nextcloud allows setting environment for
    --env PHP_UPLOAD_LIMIT=1G 
    --env PHP_MEMORY_LIMIT=2G 
when using docker / podman.

I haven't figured out how to do this with friendica.

**Comment by nupplaphil** [comment]
good idea, I'll add it

**Comment by ne20002** [comment]
This is what is written on https://github.com/nextcloud/docker for the Nextcloud image:

    PHP_MEMORY_LIMIT (default 512M) This sets the maximum amount of memory in bytes that a script is allowed to allocate. This is meant to help prevent poorly written scripts from eating up all available memory but it can prevent normal operation if set too tight.
    PHP_UPLOAD_LIMIT (default 512M) This sets the upload limit (post_max_size and upload_max_filesize) for big files. Note that you may have to change other limits depending on your client, webserver or operating system. Check the Nextcloud documentation for more information.
