### ISSUE TITLE
stack.yml - MAILNAME is not valid

### ISSUE THREAD

**Issue by nupplaphil** [friendica/docker#19]
https://github.com/friendica/docker/blob/987edd5dae0c23f0338a240d014953a00a7d5dcb/stack.yml#L29
This mailname is used for the Friendica "admin-mail".

But the e-mail isn't valid, so with [Play-with-docker](https://labs.play-with-docker.com) , we can start Friendica, but we cannot register an admin-account because of this fake-mailname (error "the email is not valid.")

**Comment by tobiasd** [comment]
Could be related to friendica/friendica#2396 and the DNS check for the email.

**Comment by nupplaphil** [comment]
I added the two lines of https://github.com/friendica/friendica/issues/2396 here with #20 :
https://github.com/friendica/docker/blob/6ba4108d3d7ea0006167e25f27e467ddcaa7dd16/.config/htconfig.php#L110-L113

Now Play-with-docker is working
