### ISSUE TITLE
Update to 2022.2: white page

### ISSUE THREAD

**Issue by ne20002** [friendica/docker#190]
Hi
Updating to 2022.2 with just pulling a new container didn't work. I now get an empty white page. This is the console output:
```
Setup MSMTP for '.. with '..' ...
Setup finished
Initializing Friendica 2022.02 ...
Upgrading Friendica from 2021.09 ...
Initializing finished
Upgrading Friendica ...
[Error] DateTimeZone::__construct(): Unknown or bad timezone (America/LosAngeles)
Upgrading finished
[10-Feb-2022 09:31:37] NOTICE: fpm is running, pid 1
[10-Feb-2022 09:31:37] NOTICE: ready to handle connections
127.0.0.1 -  10/Feb/2022:09:31:48 +0000 "GET /index.php" 200
```
TZ is set with TZ_FRIENDICA to Europe/Zurich but was America/LosAngeles in local.config.php. Changing the timezone in local.config.php to Europe/Zurich solved the problem. After restart of pod friendica 2022.2 is running.
:)

**Comment by MrPetovan** [comment]
The correct timezone name would be `America/Los_Angeles`, see https://www.php.net/manual/en/timezones.america.php

**Comment by ne20002** [comment]
Agreed
To be more precise: I didn't add America/LosAngeles to the local.config.php. I assume it has been there from the beginning (started with docker image for 2021.09). I always set the timezone with TZ_FRIENDICA env parameter.

2021.09 didn't complain about the America/LosAngeles. 2022.2 now did.

Also; I thought that the values in local.config.php are ignored if settings are in database. Seems as if the check on database value failed and it fall back to local.config.php ...
