### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by ne20002** [friendica/docker#204]
I request to add the following 
- move the location of the logfile to /var/log/friendica
- add logrotate to the image
- add a systemd unit for logrotate 

I'm using the image with Podman. Podman allows to use systemd inside the image and I'd like to have some logfile housekeeping done automatically within the image itself. I'm not sure if Docker is capable of something similar.

**Comment by nupplaphil** [comment]
@ne20002 - I'm not sure if it's the best way to handle logging inside the Docker containers. There are two different distros (alpine and debian) and I try to avoid dependencies as much as I can ..

Of course your setup would be possible, but I'm not sure what will happen when using Docker/Kubernetes specific logging mechanism on top of the logrotate principles ..

**Comment by ne20002** [comment]
I solved it for me by mouting the /var/log and created a log rotate definition on the host. Works fine so far.
