### ISSUE TITLE
Cron job with k3s acting funny

### ISSUE THREAD

**Issue by scifijunk** [friendica/docker#207]
I'm just wondering if anyone else is having an off-and-on problem with the cron job. Now what I mean by an off-and-on problem is that the cron job of worker works like normal then sometimes it would just stop like it got bord or something. Now If I post or like something then it works like normal again.

I'm just wondering if this is the way it works now or if something has been changed in the cron.sh of Friendica docker.

**Comment by nupplaphil** [comment]
@scifijunk  Can you post your config, so I can investigate how you use Friendica within your cluster? :) 
Fun-Fact: I'm currently building a k3s cluster as well, but still stuck at the some basics/infrastructure issues (newbie problems)

**Comment by scifijunk** [comment]
Well crap, I didn't even see this until now. Anyway, I think I was just impatient since I just put everything back the way it was and it just worked again.

Now when it comes to k3s you could install Portainer to start out with and then work your way to the more advanced way of doing things from there. https://docs.portainer.io/start/install/server/kubernetes/baremetal
