### ISSUE TITLE
Error: GNU Multiple Precision PHP module required but not installed.

### ISSUE THREAD

**Issue by Jeffmackinnon** [friendica/docker#211]
I created a stack in portainer with this configuration:

--------------------------------------------------------------------------------------------
version: '2'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - /volume1/docker/friendica/db:/var/lib/mysql
    environment:
      - MYSQL_USER=friendica
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=friendica
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  app:
    image: friendica
    restart: always
    volumes:
      - /volume1/docker/friendica/app:/var/www/html
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=friendica
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=friendica
      - FRIENDICA_ADMIN_MAIL=root@friendica.local      
    depends_on:
      - db

volumes:
  db:
  friendica:

------------------------------------------------------------------------------------------------

When I started the site via <ip address>:8080 I recieved the error on this page.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/29755324/198689585-5a96f115-f55a-4d70-ad6e-2dfcf3e39151.png">

I went through the available environment variables here -https://github.com/friendica/docker#possible-environment-variables but didn't see anything that would allow me to address this.

Any help you can provide is greatly appreciated.

**Comment by MrPetovan** [comment]
@nupplaphil It looks like the container needs another extension activation in the build.

**Comment by Jeffmackinnon** [comment]
After poking around for a bit I notice that the PHP: GMP (I think this is the same thing) isn't listed as a requirement on the Friendica Requirements Page - https://friendi.ca/resources/requirements/

I don't know how to test any changes to the dockerfile (still n00b) but I'm guessing that ``libgmp-dev`` needs to be added b/w lines 57 and 70 of the Debian dockerfile template - https://github.com/friendica/docker/blob/stable/Dockerfile-debian.template

**Comment by MrPetovan** [comment]
Yes, the GMP is the GNU Multiple Precision extension. Thanks for the hint about the outdated Friendi.ca requirement page. We ship a documentation with all Friendica installs and it's been updated over here (like there for example: https://friendica.mrpetovan.com/help/Install#Requirements) but we haven't taken the time to update on the website yet.

Your suggestion looks good but I'd rather have @nupplaphil 's opinion about it.
