### ISSUE TITLE
E_WARNING: session_write_close() with Redis

### ISSUE THREAD

**Issue by ne20002** [friendica/docker#213]
Since 2022-10 I get these warnings:

E_WARNING: session_write_close(): Failed to write session data using user defined save handler. (session.save_path: tcp://friendica-redis:6379)

Installation has not changed (just upgraded docker image)

**Comment by tobiasd** [comment]
part of https://github.com/friendica/friendica/issues/11993

**Comment by ne20002** [comment]
After I reinstalled my instance from scratch (2022.10 docker image) this message does no longer appear.
