### ISSUE TITLE
db.env variables are incorrect

### ISSUE THREAD

**Issue by jstevewhite** [friendica/docker#216]
The docker-compose.yaml specified mariadb as the image and does not specify a version; this results in "latest" being pulled, and the "latest" image I get does not expect "MYSQL_" variables; it expects "MARIADB_" variables. 

This results in being unable to log into the database until you change all the "MYSQL_" to "MARIADB_". 

Probably should manually set the image version or update the variable names?

**Comment by nupplaphil** [comment]
@jstevewhite sorry for the late response.

Are you sure that this isn't working?

Even the official doku uses  `MYSQL_` as "fallback" or "second" parameter:
https://hub.docker.com/_/mariadb

And I, for myself are using `MYSQL_` as well ..

**Comment by nupplaphil** [comment]
closing because one year no response :)

@jstevewhite feel free to reopen it in case you want to :)
