### ISSUE TITLE
Link in README.md is broken

### ISSUE THREAD

**Issue by PhilipMay** [friendica/docker#221]
The link in the following line in the README.md is broken:

> Using the default Image and manually setup background tasks (see Friendica [Install](https://github.com/friendica/friendica/blob/2021.03-rc/doc/Install.md#required-background-tasks))

**Comment by tobiasd** [comment]
> https://github.com/friendica/friendica/blob/2021.03-rc/doc/Install.md#required-background-tasks

The link should either go to "main" or to "develop" but not to "2021.03-rc". Maybe depending on which version of Friendica you use with Docker?
