### ISSUE TITLE
Lots of CORS errors when using the insecure image

### ISSUE THREAD

**Issue by oculos** [friendica/docker#234]
Hi,

I got the Docker composer up and running the example ("insecure", fpm), but most of the resources do not load because of CORS errors, as in the image below.

Is there a fix for this?
<img width="1473" alt="Screenshot 2023-12-09 at 18 40 39" src="https://github.com/friendica/docker/assets/6791923/2ffc39cc-76e6-4e47-bdf5-e07299c722dd">

**Comment by MrPetovan** [comment]
These aren’t CORS errors, look at the URL path, there’s one `localhost` too many, which means all these URLs end up loading an HTML 404 Not Found error instead of the Javascript files.

Please check the `config/local.config.php` for a possible `localhost/localhost` string.

**Comment by oculos** [comment]
Hi,

Thanks for the reply.

I saw that, but I just did `docker-compose -up` and configured the `FRIENDICA_URL=localhost` on the docker compose file.

Where does this come from?

**Comment by oculos** [comment]
It works now after I removed the URL setting.

**Comment by MrPetovan** [comment]
I believe the `FRIENDICA_URL` setting must be a fully-qualified URL like `https://localhost`.
