### ISSUE TITLE
Help on running Friendica on Kubernetes

### ISSUE THREAD

**Issue by oculos** [friendica/docker#235]
Hi,

I am sorry that I post this here, I didn't find anywhere I could find this info.
I am planning to deploy a Friendica instance on Kubernetes.
My questions are:

- In order to scale in the future, is it enough to scale the amount of replicas of the app image? And of the web image as well?
- Is redis necessary? I saw some of the examples have it, some don't.

**Comment by MrPetovan** [comment]
Redis is optional, it just is one of the few cache backends Friendica supports. I believe that in an auto-scaling context having an independent Redis cache backend can speed up the whole cluster but I’d refer to @nupplaphil

**Comment by nupplaphil** [comment]
Redis is a high-performance distributed key-value storage and it's a best practice to use it for container session handling.
tbh I copied and adapted most of the functionality from Nextcloud :)

I added my setup as a possible guideline, how Redis can be used
