### ISSUE TITLE
FRIENDICA_UPGRADE cannot be false on rc image

### ISSUE THREAD

**Issue by oculos** [friendica/docker#237]
Hi,

I use the fpm image, and had to upgrade it to rc-fpm as there was a lot of errors with php.

I then set FRIENDICA_UPGRADE=true, so that the image would run.

But after the upgrade, the image won't restart if I set "FRIENDICA_UPGRADE=false". Having it as "true" makes restarting a container too slow:

```
No new Friendica sources found (enable FRIENDICA_UPGRADE for new sources)                                                            │
│ Can't copy Friendica sources because the version of the data (2023.09-rc) is higher than the docker image (0.0.0.0)
```

Any clues on what to check here?

**Comment by MrPetovan** [comment]
Paging @nupplaphil

**Comment by oculos** [comment]
Looks like this is fixed on 2023-12-fpm image
