### ISSUE TITLE
PHP Module IntlChar is missing

### ISSUE THREAD

**Issue by doskel** [friendica/docker#241]
Hey all! Trying out Friendica and doing the docker install, and while everything starts up fine, the web check complains about IntlChar being missing. I've poked around a touch in the container and tried to enable it manually, but to no avail; I think this is a container image issue. 
![image](https://github.com/friendica/docker/assets/135243546/3b390f33-b495-4d12-866d-b1c90f3a1048)

**Comment by MrPetovan** [comment]
Thank you for the report, we added this requirement in the last stable version of the platform but the image wasn't updated accordingly. Unfortunately I don't know enough about Docker to make this change, usually @nupplaphil does it but his availability is spotty, thank you for your patience.

**Comment by nupplaphil** [comment]
I'll have a look tomorrow.

**Comment by doskel** [comment]
Hey, sorry to bother, but I was just wondering what the status on this is?

**Comment by RamXX** [comment]
Hey folks. Hitting the same issue. I'd rather avoid having to do a full direct install and I'd prefer to rely on the Docker image if possible. I'm trying to determine if Friendica would be a better replacement for Nextdoor for a local, non-federated community but with the local image failing, it's a non-starter until this problem is resolved... any help will be greatly appreciated. Thank you in advance!

**Comment by Fleker** [comment]
The fix is small. Here's what I changed in `2023.12/apache/Dockerfile`:

```
    docker-php-ext-install -j "$(nproc)" \
        pdo_mysql \
        gd \
        exif \
        zip \
        opcache \
        ctype \
        pcntl \
        ldap \
        gmp \
        intl \
    ;
```

**Comment by alekslynx** [comment]
Hi, The Image still doesn't work. Do you have any news?

**Comment by petersem** [comment]
Any updates on this? The docker implementation is basically screwed until this is fixed.

**Comment by MrPetovan** [comment]
The module has reportedly been added in https://github.com/friendica/docker/pull/243, not sure about the Docker image update process.
