### ISSUE TITLE
2024.03-rc image is missing

### ISSUE THREAD

**Issue by ne20002** [friendica/docker#244]
I'm missing a 2024.03-rc image at hub.docker.com. Is this intended or do we have another source / repository?

**Comment by MrPetovan** [comment]
Paging @nupplaphil

**Comment by Sarahlizzy** [comment]
> Paging @nupplaphil

Doesn’t look like he’s been active here since the new year. Hope he’s ok.

**Comment by annando** [comment]
Yeah, he is currently inactive. It would be great, if someone could take over who has got some experience in docker. Sadly for me this is a completely unknown area.

**Comment by Sarahlizzy** [comment]
I have a bit of experience building docker images, but zero experience building Friendica.

**Comment by nupplaphil** [comment]
Hi there,

I'm sorry for my long delay. It was a stressful time the last 6 months for me. I guess at least I can maintain the docker images, but I would love to have others, like @Sarahlizzy which can help me :-)

I created the new image: https://github.com/docker-library/official-images/pull/16343

After the merge of the PR, the Docker images should get built automatically.

 @Sarahlizzy - There is a description at https://github.com/friendica/docker/blob/stable/README-MAINTENANCE.md how to maintain the images of this repo. Maybe you can check if it's understandable for others than me. If so, it'd be great if you can help me :-)

**Comment by Sarahlizzy** [comment]
Glad to hear you’re still about. Sorry to hear things have been stressful. 

My partner and I will have a look at your info. We’re both keen to help. I’m probably a bit out of my depth but can likely learn. My partner has rather more experience. 

Bit busy for the next few days, but we will have a look at it. 

Thanks once again, and I hope things get better.

**Comment by nupplaphil** [comment]
thank you for your warm words and your help! :-)

**Comment by nupplaphil** [comment]
Fixed :)
