### ISSUE TITLE
`friendica:2024.08-fpm-alpine` fails to build on i386

### ISSUE THREAD

**Issue by yosifkit** [friendica/docker#269]
Because the base image, `php:8.1-fpm-alpine`, recently updated to Alpine 3.21, some modules now fail to build on `i386`, `arm32v7`, and `arm32v6`. The `memcached` module is the one that is currently failing. It is caused by Alpine 3.21 using `gcc` 14 which changed `incompatible-pointer-types` to an error instead of just a warning (https://gcc.gnu.org/gcc-14/porting_to.html). Luckily `php-memcached` already has a fix in [in 3.3.0](https://github.com/php-memcached-dev/php-memcached/commit/899f0d52425b3efe2f67ed73eca115a0b5dc6c34), so just a bump to the `pecl install memcached` should be enough to fix it.

It looks like your Dockerfile for `friendica:2024.08-fpm-alpine` already has the new `memcached` module, so I think we just need the reference updated for the `2024.08` images in https://github.com/docker-library/official-images/blob/master/library/friendica.
https://github.com/friendica/docker/blob/365f4797cc665d6d70ab536ab19b9567adb9c919/2024.08/fpm-alpine/Dockerfile#L87

[build log:](https://github.com/docker-library/meta/actions/runs/12287142322/job/34288630432)
```console
#10 111.6 /tmp/pear/temp/memcached/php_memcached.c: In function 's_compress_value':
#10 111.6 /tmp/pear/temp/memcached/php_memcached.c:903:65: error: passing argument 2 of 'compress' from incompatible pointer type [-Wincompatible-pointer-types]
#10 111.6   903 |                         int status = compress((Bytef *) buffer, &compressed_size, (Bytef *) ZSTR_VAL(payload), ZSTR_LEN(payload));
#10 111.6       |                                                                 ^~~~~~~~~~~~~~~~
#10 111.6       |                                                                 |
#10 111.6       |                                                                 size_t * {aka unsigned int *}
#10 111.6 In file included from /tmp/pear/temp/memcached/php_memcached.c:38:
#10 111.6 /usr/include/zlib.h:1232:53: note: expected 'uLongf *' {aka 'long unsigned int *'} but argument is of type 'size_t *' {aka 'unsigned int *'}
...
```

**Comment by ne20002** [comment]
Thank you for the report. I'll do an update and PR today.

**Comment by MrPetovan** [comment]
Thanks @yosifkit for the detailed report and @ne20002 for acting on it!
