### ISSUE TITLE
Switch to local.config.php

### ISSUE THREAD

**Issue by nupplaphil** [friendica/docker#38]
Switching back to `local.config.php` because of https://github.com/friendica/friendica/pull/6199/

@MrPetovan This change is making a lot of things easier here :-). There would have been a ugly workaround for custom ini.php files necessary instead.

**Comment by MrPetovan** [comment]
I'm glad it does, that's why I made this call even though we changed the config file format last stable release as well.

**Comment by MrPetovan** [comment]
Isn't 3. comparable to 1. anyway?

For 4., there's the issue of config file load order. This is why all config files are named, they are read in order and overwrite existing values (or not, for defaults).

I'd instinctively be in favor or 2. mainly because it feels less disruptive but I admit I don't have a full grasp of the implications.

**Comment by nupplaphil** [comment]
Yes, the only difference is the source. At 1. it's environment variables, 2. is with another config.

To be honest I started option 4 and came to the point with the order too, that's why I stopped and added the discussion here ;-).

Yes, 2 would be the most less impact on the codebase and it would be entirely controllable with docker configurations. So I will start this path.

Maybe the script is good enough even for the Friendica codebase (`bin/loadenv.php` which adds all environment variables starting `FRIENDICA_*` to the config). I'll give it a try :-)
One hard thing will be the additional categories.
Is there a official shortcut for "FRIENDICA" ? (f.e. FRD?)

They would look like f.e.:
-     `FRD_SYS_ALWAYS_SHOW_PREVIEW`
-     `FRD_SYS_BLOCK_LOCAL_DIR`
-     `FRD_SYS_CACHE_DRIVER`
-     `FRD_EXP_EXP_THEMES`
-     `FRD_THM_HIDE_EVENTLIST`
...

**Comment by MrPetovan** [comment]
`FRND` maybe? Although it may be too close from `DFRN`, the acronym of the decentralized protocol Friendica is built upon.

**Comment by nupplaphil** [comment]
Prerequisite: https://github.com/friendica/friendica/pull/7310

**Comment by nupplaphil** [comment]
Should get fixed by #70
