### ISSUE TITLE
Docker image on ARM architecture

### ISSUE THREAD

**Issue by valvin1** [friendica/docker#55]
Hello,

As I'm having trouble on my x86_64 server in reason of having only 2GB of RAM and my friendica instance requires almost 1GB with server + mariadb I was looking for hosting friendica on a ARM architecture which is cheaper than x86.

Unfortunately MariaDB runs well but it is not the same for the server. I've tried several different image but each time I get the same result. Is there a trick to do this or maybe it's not possible ?

thank you.

**Comment by valvin1** [comment]
if I refer to nextcloud it uses `armhf/php:7.1-fpm` as a based image but maybe there are other dependencies which are not compatible ?

**Comment by valvin1** [comment]
and additionnal info because I'm not so aware about architecture so here is the targeted host `docker system info` : 

```
Kernel Version: 4.9.93-mainline-rev1
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: aarch64
CPUs: 6
Total Memory: 3.853GiB
```

**Comment by MrPetovan** [comment]
> I've tried several different image but each time I get the same result.

What is the result you're getting?

**Comment by valvin1** [comment]
something like : 

```
docker logs friendicaapp
standard_init_linux.go:207: exec user process caused "exec format error"
```

**Comment by nupplaphil** [comment]
Thank you for your report :-)

Currently, the docker images doesn't support ARM architectures, because they need to base on a ARM docker image too. I'll have a look if I can create easily.

**Comment by nupplaphil** [comment]
I'm afraid, this can't be easily done. So it remain in my backlog, but not as a todo for the next weeks :-)

**Comment by valvin1** [comment]
no problem, i've solved my main issue with RAM consumption so I can stay on my x86 server :)

**Comment by nupplaphil** [comment]
Interesting article, which may help for this task:
https://techcrunch.com/2019/04/24/docker-partners-with-arm/amp/

**Comment by nupplaphil** [comment]
@valvin1 there's now a official Friendica image with arm support available.

Just use the `friendica` image on the arm device :)

**Comment by valvin1** [comment]
oh nice, I haven't followed your work for the official docker image. Great job ! :)
