### ISSUE TITLE
Warning: dns_get_record(): A temporary server error occurred. in /var/www/html/include/dba.php on line 58

### ISSUE THREAD

**Issue by jaltek** [friendica/docker#6]
Hi,

I tried to setup a friendica instance by using the docker-compose variant (Base version - FPM).
By using the install wizard I got an error during the database initialization:

> Warning: dns_get_record(): A temporary server error occurred. in /var/www/html/include/dba.php on line 58

So I think the dns_get_record() function cannot handle the "db" hostname from the database.

So I digged a little around in the app container:
```
# dig db

; <<>> DiG 9.9.5-9+deb8u15-Debian <<>> db
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5959
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;db.                            IN      A

;; ANSWER SECTION:
db.                     600     IN      A       172.19.0.2

;; Query time: 1 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Wed May 23 10:08:20 UTC 2018
;; MSG SIZE  rcvd: 38
```

Using the PHP function:
```
# php -r "var_dump(dns_get_record('db', DNS_A + DNS_CNAME + DNS_PTR));"

Warning: dns_get_record(): A temporary server error occurred. in Command line code on line 1
bool(false)
```
Using the PHP function without ```DNS_PTR```

```
# php -r "var_dump(dns_get_record('db', DNS_A + DNS_CNAME));"
array(1) {
  [0]=>
  array(5) {
    ["host"]=>
    string(2) "db"
    ["class"]=>
    string(2) "IN"
    ["ttl"]=>
    int(600)
    ["type"]=>
    string(1) "A"
    ["ip"]=>
    string(10) "172.19.0.2"
  }
}
```

So there seems to be an issue whith the PTR lookup inside the docker container...

**Comment by nupplaphil** [comment]
Ah, thank you!

I know this type of issue. I had it with the automatic installation too.
Therefore I wrote a workaround for it. I will create a PR to update it to the "normal" installation wizard too.

See:
https://github.com/friendica/docker/blob/1e6852cd9a8b77a1245ac523aef2c9ed93cbbe63/stable/fpm/bin/friendica#L163

**Comment by jaltek** [comment]
@nupplaphil Sorry. My fault. I meant the "Base version - apache". I copied the wrong YAML source :)
The FPM image seems to have other problems which are IMHO caused by the line 
```
 volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
```
(Maybe a separate issue?)

**Comment by nupplaphil** [comment]
I updated friendica/server:apache as well :-)

other Issue: yes, please do so. I'd love to make the environment more stable.

**Comment by jaltek** [comment]
Installation worked :tada: 
So I think this can be closed.

**Comment by nupplaphil** [comment]
@jaltek 
Could you do me a favor? Could you please pull the latest friendica/server:apache and try if it works for you?

We fixed the issue not with my "dirty hack". We fixed it at the friendica codebase itself and I pushed this change to the current images.

For me, it is working locally

**Comment by MrPetovan** [comment]
Good to know, closing the issue.
