### ISSUE TITLE
testing 2019.06-rc but still on 2019.04

### ISSUE THREAD

**Issue by valvin1** [friendica/docker#62]
I have tried updating my friendica docker installation from `friendica/server:latest` which was 2019.04 to `friendica/server:2019.06-rc`

after upgrading everything looks fine but i'm still in version 2019.04 in admin panel. 

inside the container it looks ok : 
```
env|grep FRIEN
FRIENDICA_VERSION=2019.06-rc
FRIENDICA_ADDONS=2019.06-rc
``` 

on docker host : 
```
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                NAMES
4d03e4f41680        friendica/server:2019.06-rc   "/cron.sh"               43 minutes ago      Up 13 minutes       80/tcp                               friendicacron
3bc23e5046c6        friendica/server:2019.06-rc   "/entrypoint.sh apac…"   44 minutes ago      Up 17 minutes       127.0.0.1:8088->80/tcp               friendicaapp
```

but in admin panel i'm still having 2019.04 : 

![Screenshot_20190521_220120](https://user-images.githubusercontent.com/1267915/58126772-02d1ba00-7c14-11e9-8ebb-e61d6a7f2278.png)

Do i have miss something in the upgrade operation ?

**Comment by MrPetovan** [comment]
I would guess that the version number hasn't been updated somewhere in the chain.

**Comment by valvin1** [comment]
yes i confirm :  

here is what i have inside the container : 
```
cat CHANGELOG 
Version 2019.04 (2019-04-28)
  Friendica Core:
    Fixed a privacy problem with postings accessed by feed [MrPetovan]

```

but when i do : 

```
curl -fsSL -o friendica.tar.gz "https://github.com/friendica/friendica/archive/2019.06-rc.tar.gz"
```

CHANGELOG is ok : 

```
Version 2019.06 (UNRELEASED) (2019-06-?)
  Friendica Core:
    Update to the tranlation (CS, DE, ET, PL, PT-BR, SV) [translation teams]
    Update to the documentation [nupplaphil, realkinetix]
[...]
```

So current process is not downloading the good archive or I have to do something to update my volume ?

**Comment by MrPetovan** [comment]
I'm not sure yet, thanks for the elaboration, I'm not experienced enough with Docker to help you, paging @nupplaphil

**Comment by valvin1** [comment]
after reading entrypoint.sh it looks like when we are in `-rc` or `-dev` we have to setup an additional environment `FRIENDICA_UPGRADE` to true because inside the container : 

```
cat /usr/src/friendica/VERSION
cat: /usr/src/friendica/VERSION: No such file or directory
```

or the issue is why /usr/src/friendica folder doesn't exist.

**Comment by valvin1** [comment]
I confirm that the environment FRIENDICA_UPGRADE solved the issue.

And it was in the README but I don't see it : 

```
Develop/Release Candidat Settings

    FRIENDICA_UPGRADE If set to true, a develop or release candidat node will get updated at startup.
```

**Comment by MrPetovan** [comment]
Congrats! Do you need any further help? If not, you can close this issue.

**Comment by valvin1** [comment]
nope its ok :)
