### ISSUE TITLE
Roll mysql into the container

### ISSUE THREAD

**Issue by 2018robert** [friendica/docker#63]
It'd be great if this container just worked without additional configuration. Please consider rolling mysql into the container.

**Comment by nupplaphil** [comment]
Thanks for your suggestion. You could create a container image, based on this image and include an mysql server with standard configs in it.

Something like (just an example, not ready!)
```docker
FROM friendica/server:apache

RUN set -ex; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        mysql-server \
    ; \
    rm -rf /var/lib/apt/lists/*; \

ENV MYSQL_HOST localhost
ENV MYSQL_USERNAME friendica
ENV MYSQL_PASSWORD s0up3rS3Cure
ENV MYSQL_DATABASE friendica
```

But there are some parts, which we have to consider:
- The official MySQL image has some more setup-scripts, which we shouldn't copy into this repository (so we need a friendica-focused setup script ..)
- The background cronjob for the daemon has to run at least as a separate process (There's already a "supervisor" container which enables a multi-process run here https://github.com/friendica/docker/tree/master/.examples/dockerfiles/cron/apache )

But I'm with you, I started creating such a "out-of-the-box" image.
Meanwhile, I hope someday Friendica gets a "SQLite" support, so we don't have to include a full-blown mysql-server ;-)

**Comment by 2018robert** [comment]
Sounds great. Thanks for the reply :)
