### ISSUE TITLE
Cannot start service webserver: OCI runtime create failed

### ISSUE THREAD

**Issue by nupplaphil** [friendica/docker#65]
_Originally posted by @pianic26 in https://github.com/friendica/docker/issues/8#issuecomment-498503241_

> I have the same problem; I'm new with docker and I don't how to fix please help
ERROR: for firstproject-webserver  Cannot start service webserver: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/c/firstproject/phpdocker/nginx/nginx.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/ccb70cb832f49a81d583eb3e389371e01865cb6ab9ae7dd4a923d4f434a9361c/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/ccb70cb832f49a81d583eb3e389371e01865Creating firstproject-php-fpm   ... done
u trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected tCreating firstproject-mysql     ... done
[docker-compose.txt](https://github.com/friendica/docker/files/3250344/docker-compose.txt)

**Comment by nupplaphil** [comment]
@pianic26

Did you create a `nginx.conf` file inside the subdirecoty `nginx`?
Can you paste you `docker-compose.yml` file for better support?

**Comment by musznik** [comment]
same problem here using this docker-compose

`# This docker-compose config for ArchiveBox runs the following containers:
#     - ArchiveBox (it creates the initial archive, then sleeps forever to allow commands to be run with exec to add links)
#     - nginx webserver running on https://127.0.0.1:8098
# Usage:
#     docker-compose up -d
#     echo "https://example.com" | docker-compose exec -T archivebox /bin/archive
#     docker-compose exec archivebox /bin/archive https://example.com/some/feed.rss
# Documentation:
#     https://github.com/pirate/ArchiveBox/wiki/Docker#docker-compose

version: '3'

services:
    archivebox:
        build: .
        stdin_open: true
        tty: true
        # env_file: path/to/your/ArchiveBox.conf
        environment:
            - USE_COLOR=False
            - SHOW_PROGRESS=False
        volumes:
            - ./data:/data
        command: bash -c 'echo "https://github.com/pirate/ArchiveBox" | /bin/archive; tail -f /dev/null'

    nginx:
        image: 'nginx'
        ports:
            - '8098:80'
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./data:/var/www
`

`# This docker-compose config for ArchiveBox runs the following containers:
#     - ArchiveBox (it creates the initial archive, then sleeps forever to allow commands to be run with exec to add links)
#     - nginx webserver running on https://127.0.0.1:8098
# Usage:
#     docker-compose up -d
#     echo "https://example.com" | docker-compose exec -T archivebox /bin/archive
#     docker-compose exec archivebox /bin/archive https://example.com/some/feed.rss
# Documentation:
#     https://github.com/pirate/ArchiveBox/wiki/Docker#docker-compose

version: '3'

services:
    archivebox:
        build: .
        stdin_open: true
        tty: true
        # env_file: path/to/your/ArchiveBox.conf
        environment:
            - USE_COLOR=False
            - SHOW_PROGRESS=False
        volumes:
            - ./data:/data
        command: bash -c 'echo "https://github.com/pirate/ArchiveBox" | /bin/archive; tail -f /dev/null'

    nginx:
        image: 'nginx'
        ports:
            - '8098:80'
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./data:/var/www
`

**Comment by pianic26** [comment]
yes it's created and already attaches as docker-compose.txt

**Comment by nupplaphil** [comment]
@pianic26 I close this issue. The attached docker-compose file you gave doesn't include the friendica docker image at all :-) I think you need another docker-compose file. Have a look at `.examples` (after I fixed #134 ;-) ).
