### ISSUE TITLE
Ready for official image?

### ISSUE THREAD

**Issue by nupplaphil** [friendica/docker#74]
I'd like to push this image to the official repository since it evolved a lot and I know at least 2 other people using it regulary ;-) .

This will also solve #55 , because the official repository is capable of building multi-architecture images out of the box.

**Comment by MrPetovan** [comment]
Go for it!

**Comment by annando** [comment]
friendica.feneas.org is running with this as well.

**Comment by nupplaphil** [comment]
Done :)))))))

**Comment by MrPetovan** [comment]
Yay!

**Comment by nupplaphil** [comment]
https://hub.docker.com/_/friendica we're now an official image at the docker hub :)
