### ISSUE TITLE
Deduplicate dependencies

### ISSUE THREAD

**Issue by J0WI** [friendica/docker#77]
Some dependencies and extensions are already provided by the base image, so there's no need to add them again:

https://github.com/friendica/docker/blob/af1aa857f6867ee394a07d7f93a2c06091836dc9/2019.06/fpm-alpine/Dockerfile#L55-L67
https://github.com/docker-library/php/blob/d367f7fb843c23f265f732256bb196b160523cd2/7.3/alpine3.10/fpm/Dockerfile#L134-L145

**Comment by nupplaphil** [comment]
Will be fixed by #78
