### ISSUE TITLE
Crash when using 2019-09-rc after the release

### ISSUE THREAD

**Issue by valvin1** [friendica/docker#81]
This morning my instance crashes after a reboot. 

After a quick investigation it is because when using a RC tag version at startup changes are pulled. Unfortunately this morning `2019-09-rc` branch was not present anymore which leads to a crash.

I think it would be interesting in case of a git pull issue to fallback in previous version without crash.

**Comment by nupplaphil** [comment]
mhm ... That's true .. I will add a check if the branch is available and just make a clone if its possible..

Thanks for the input

**Comment by valvin1** [comment]
Thank you :)
