### ISSUE TITLE
Apache image can't utilize ldapauth addon because container lacks `libldap2-dev`

### ISSUE THREAD

**Issue by victort** [friendica/docker#83]
`friendica.log` renders:
```
2019-11-12 10:25:08 index [INFO]: ldapauth: not configured or missing php-ldap module [] - {"file":"ldapauth.php","line":105,"function":"ldapauth_authenticate","uid":"3c55bf","process_id":39}
```
for example, after my trying to fill out and run an `addon.config.php` with an `ldapauth` block.

**Comment by victort** [comment]
actually, it looks like it might be `libldap2-dev` that's missing, because 
```
root@4a678cd31a50:/var/www/html# docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/
```
fails during `configure` on
```
configure: error: Cannot find ldap.h
```

but succeeds when `libldap2-dev` is present. I'm still trying to work out if it's both the `php7.3-ldap` and `libldap2-dev` packages are required, or just the latter. stay tuned.

**Comment by victort** [comment]
so, I get ldap to appear among the phpe extensions in `phpinfo()` now, with the following in my `Dockerfile` (which is really just wrapping `friendica/server` with my (among other things) `/var/www/html/config/addon.config.php` so i can LDAP),
```
## compensate for missing php stuff
RUN apt-get update ; apt-get install --no-install-recommends -y libldap2-dev
RUN docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/; docker-php-ext-install ldap
```

**Comment by nupplaphil** [comment]
Ah thx .. I'll have a look!

**Comment by nupplaphil** [comment]
You don't have to add the dependency by your own. I think it's tiny enough to add it to the base image.

So I added them -> see #84
